version: "3.9"

services:
  dwh_pipeline:
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: crbigdatadev7.azurecr.io/hr_pipeline:latest

  dashboard:
    build:
      context: .
      dockerfile: dockerfile.dashboard
    image: crbigdatadev7.azurecr.io/hr_dashboard:latest
    ports:
      - "8501:8501"